### ISSUE TITLE
Do you have deserialization C2S data format?

### ISSUE THREAD

**Issue by killshadow** [nfcgate/nfcgate#100]
I want to rebuild nfcgate in order to get rid of server that only need two phones to exchange apdu message through wifi. How can I deserialization `C2S.java` or do you have original data?

**Comment by roussosalex** [comment]
You can host the python server on one phone using [Termux](https://github.com/termux/termux-app) and do not need to rebuild NFCGate. If you still want to do it, you can find the original protobuf files [here](https://github.com/nfcgate/protocol).

**Comment by killshadow** [comment]
Thanks for your advice. I had tried use Termux, but it's still a little bit complicated( Download `tsu`, install python and so on).
