### ISSUE TITLE
Support for Android 10

### ISSUE THREAD

**Issue by kleest** [nfcgate/nfcgate#107]
Function hooking requires modifications for Android 10 compatibility:

- [x] C++ mangled symbol names
- [x] Execute-only memory (XOM)
- [x] Control flow integrity (CFI) (?)

This means that any mode using function hooking does not work on 10: clone mode, tag role of relay and replay mode. On-device capture mode and reader roles are **not** affected.

**Comment by roussosalex** [comment]
Added with e84644f0d7cae8b3b43991ddf4eb9371688e2ede
