### ISSUE TITLE
Samsung S8 and one plus 5T for relay and no response

### ISSUE THREAD

**Issue by quark9981** [nfcgate/nfcgate#109]
hello
I used Samsung S8 and one plus 5T for relay and no response. Have you ever encountered any reason?Would you please tell me what type of mobile phone you used for the test?

**Comment by roussosalex** [comment]
Could you provide us with the NFCGate status page for the devices you used? For our tested devices and Android versions, see the [compatibility document](https://github.com/nfcgate/nfcgate/blob/v2/doc/Compatibility.md).

**Comment by quark9981** [comment]
![Screenshot_20200913-110847](https://user-images.githubusercontent.com/42036273/93009288-b1d89880-f5b1-11ea-99ab-117dd927d151.png)
![Screenshot_20200913-110608](https://user-images.githubusercontent.com/42036273/93009289-b309c580-f5b1-11ea-9026-f2bfcf41daec.png)
Replace it with two Nesux 5x, replay and relay still fail, this is a screenshot of my device.
![Screenshot_20200913-111311](https://user-images.githubusercontent.com/42036273/93009319-2ca1b380-f5b2-11ea-82e8-e63c369ad184.png)

**Comment by quark9981** [comment]
The problem has been solved. Thank you for your support

**Comment by Thor-Heimdallr** [comment]
> 
Cool , How did you solve it ?
