### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by ghost** [nfcgate/nfcgate#110]
Hello,

I really don't know how to solve this problem: **ld.lld: error: cannot find entry symbol xecute-only; defaulting to 0x2D824**

https://prnt.sc/wnn2ly

Thanks really if you know how to fix it

Yours truly,

**Comment by roussosalex** [comment]
Looks like this may be an incompatibility with the latest NDK (r22). Could you test if using the previous version (LTS r21d) fixes this issue?

**Comment by ghost** [comment]
Ohhh thank you so much, I hadn't thought of that.
Compilation ok,
thank you so much

**Comment by JustinGirard** [comment]
This also worked for me. I had the same issue.
