### ISSUE TITLE
F-Droid packaging

### ISSUE THREAD

**Issue by Iey4iej3** [nfcgate/nfcgate#115]
Hello developers,

I would propose the inclusion of this app into the F-Droid repo. I expect that you could open an issue on https://gitlab.com/fdroid/rfp/-/issues and cooperate with them to get NFCGate on it. Thanks!

Best,

**Comment by linsui** [comment]
@kleest I can help package NFCGate for F-Droid. How can I build https://github.com/nfcgate/nfcgate/blob/v2/nfcd/libs/XposedBridgeApi-20150213.jar? It seems to be a very old lib.

Edit: The lib is not used.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15177 It will be published on F-Droid in few days.

**Comment by benmordecai** [comment]
Is there any guidance on how to get the required modules (Xposed) when using the F-droid package? The two xposed projects on the readme appear to be dead. EdXposed was last released in 2021 and LSPosed is now a public archive. Is root required?

**Comment by linsui** [comment]
No, the F-Droid apk is exactly the same as the one in GitHub release. Root is required for some functions. You can use a fork of LSPosed or wait until LSPosed is revived.

**Comment by kleest** [comment]
Thanks to @linsui NFCGate [is now available on F-Droid](https://f-droid.org/packages/de.tu_darmstadt.seemoo.nfcgate)! I will close this issue.
