### ISSUE TITLE
NFCGATE on WearOS  NFC(HCE) SUPPORT

### ISSUE THREAD

**Issue by WearOS-NFC** [nfcgate/nfcgate#125]
WearOS smartwatches with NFC only support NFC payment (Card emulation mode), not NFC tag reading (Reader/Writer mode) . Is this true?
I've heard this is an WearOS issue that Google need to allow Reader/Writer mode from OS level before I can develop a smartwatch NFC tag app. Is this true? I see Android smartphones all support NFC tag reading/writing (Reader/Writer mode), either natively or via app and Android OS open to NFC app development through API and device.

This will be a real roadblock if it is true that WearOS smartwatch can't read/write NFC tags due to WearOS restriction.

PS. I managed to open nfcgate but with nfc closed. When I toggle on nfc , nfcgate crash. I heard manifest is incorrect for WearOS???? Strange thing smart card emulator https://frankmorgner.github.io/vsmartcard/ACardEmulator/README.html  works with nfc toggled on. ( did not test actual functionality) . Last thing is possible root on samsung galaxy watch 4? Any help will be much appreciated.  🙌 

![20230312_095710](https://user-images.githubusercontent.com/127653159/224532102-0fa3f89b-4266-49d7-be49-32370a8f5eab.jpg)
![20230312_095643](https://user-images.githubusercontent.com/127653159/224532105-e4bedf58-ed51-4e00-978d-efd18957d6a6.jpg)
![20230312_095655](https://user-images.githubusercontent.com/127653159/224532108-3a512a92-f061-4991-b539-8b6b4b7b1497.jpg)
![20230312_095629](https://user-images.githubusercontent.com/127653159/224532110-85e54f1b-4165-44f4-b416-1bb7caa1ecd4.jpg)
![20230312_095605](https://user-images.githubusercontent.com/127653159/224532112-98019af2-3331-458f-becd-1ac9a2e40bcb.jpg)
![20230312_095725](https://user-images.githubusercontent.com/127653159/224532116-460fd6b5-aace-46ad-8642-b40b53548223.jpg)
![20230312_095800](https://user-images.githubusercontent.com/127653159/224532119-0e89bd37-ad11-4c43-becc-f152b1e0e457.jpg)
![20230312_095810](https://user-images.githubusercontent.com/127653159/224532121-9670c7d3-8dd8-4801-99e7-b06eea8a7587.jpg)
![20230312_095848](https://user-images.githubusercontent.com/127653159/224532124-a6c03b70-fb75-45be-9f82-a94a2588dfea.jpg)
![20230312_095904](https://user-images.githubusercontent.com/127653159/224532125-3d2ff1a0-00a9-4845-83b3-81ee10aa37da.jpg)
![20230312_100000](https://user-images.githubusercontent.com/127653159/224532127-39322ceb-4950-4622-acfb-d1a74105719a.jpg)
![20230312_100009](https://user-images.githubusercontent.com/127653159/224532130-21659c3b-ef49-4ed0-8743-9413bbd94be7.jpg)
![20230312_100101](https://user-images.githubusercontent.com/127653159/224532133-32960a7d-5187-4b45-9d69-b80da2f969f6.jpg)
![20230312_100122](https://user-images.githubusercontent.com/127653159/224532134-16a79030-3cce-4001-bd08-e304e9dd5e8a.jpg)

**Comment by WearOS-NFC** [comment]
@kleest @malexmave @DanielAW  @UweM 

ANY SUPPORT ON THIS ISSUE??

KEEP UP THE GOOD WORK BLESSINGS

**Comment by kleest** [comment]
NFCGate depends on the NFC capabilities and APIs that are provided by the operating system. So, using wearOS as a reader device might not be possible due to hardware limitations (cf. https://issuetracker.google.com/issues/213599626). If HCE APIs are available for "regular" apps (not only the system-provided payment apps), using NFCGate on a wearOS device as tag in relay or replay mode should be possible. However, for emulation of static tag data, root access and an Xposed-compatible hooking framework is required, which is not that common on wearOS devices.

**Comment by WearOS-NFC** [comment]
Too bad they limit the device 😪,  thanks for clarification.

**Comment by Flipo82** [comment]
Hi @kleest , THIS GUY USES GW4 AND GW6 TO EMULATE A TESLA KEYFOB.
https://github.com/pccr10001/TeslaWearKey
I think issue have been fix under the radar and if you have the right AndroidManifest.xml( check out above link) apps should now work.???
Is this correct ? I try now 2.4.2 on gw4 and it only opens when nfc is turned off but after it opens you can toggle nfc on again and app show green except xposed with is normal as it is not rooted yet ( https://xdaforums.com/t/rooting-galaxy-watch4.4452343/page-3 ),when i try to relay app crash and also clone mode dont detect nfc card this is expected as wearos limitation for reading. Is this to do with <uses-feature android:name="android.hardware.type.watch"/> or android:name="android.hardware.nfc.hce" . Thanks

**Comment by kleest** [comment]
@Flipo82 HCE was never an issue, not all wearOS devices can read tags. NFCGate needs changes to support such devices.
