### ISSUE TITLE
Include in NetHunter Store

### ISSUE THREAD

**Issue by yesimxev** [nfcgate/nfcgate#128]
Thank you for your awesome work! If you don't mind, we'd like to add this app to the NetHunter Store. Please let me know if there are any concerns 🙏

**Comment by kleest** [comment]
This is fine as long as you comply to the license, which is currently Apache License Version 2. Feel free to reach out in case of problems. Happy to see this added to the NetHunter Store :slightly_smiling_face:

For future reference: https://gitlab.com/kalilinux/nethunter/store/rfp/-/issues/15
