### ISSUE TITLE
native hook doesn't work in xiaomi redmi note 11 pro+

### ISSUE THREAD

**Issue by zimakkkk** [nfcgate/nfcgate#138]
![Screenshot_2023-10-12-16-46-32-564_de tu_darmstadt seemoo nfcgate](https://github.com/nfcgate/nfcgate/assets/68278324/b4d01071-6a5b-43bc-ab3f-508b776842b9)

Device: xiaomi redmi note 11 pro+
OS: stock miui rom. v14.0.5.0 eu

[log2.txt](https://github.com/nfcgate/nfcgate/files/12882918/log2.txt)

**Comment by roussosalex** [comment]
Looks like the image for this device does not contain any "lib*nfc*nci.so". It seems that the lib is directly loaded from an APK. Can you check that 

1. your filesystem does not contain any "lib*nfc*nci.so"?

**Comment by roussosalex** [comment]
Thanks for reporting this issue! Looks like the image for this device does not contain any "lib\*nfc\*nci.so" and that the lib is directly loaded from an APK. Can you check that:

1. your filesystem does not contain any "lib\*nfc\*nci.so"?
2. you have the `NQNfcNci.apk` (probably in `/product/pangu/system/app/NQNfcNci/NQNfcNci.apk`)
3. the `NQNfcNci.apk` contains the file `lib/arm64-v8a/libsn100nfc-nci.so` or similar

If this is the case, NFCGate might have to be adapted to expect to find the library in memory and no longer in the filesystem.

**Comment by zimakkkk** [comment]
i checked in /system/lib/ and there was no "lib\*nfc\*nci.so".
and the app and library inside the app exist.

**Comment by RandLily** [comment]
same as my note12-turbo and note11t-pro

**Comment by roussosalex** [comment]
Work on this issue is in progress. Updates will follow.

**Comment by roussosalex** [comment]
We have made some changes on the development branch (28a89c9ab8e8298c7df716a047c9cf481a64aed6) that should fix this issue. Could you test it and report if it works? If not, please provide a log as above. Thanks!

**Comment by wait-what** [comment]
I have a similar xiaomi device with the same issue, same nfc chip and no such library in /system/lib. Can you please send a prebuilt package so that I could test it?

**Comment by i404788** [comment]
@roussosalex Also had this issue, building from https://github.com/nfcgate/nfcgate/commit/28a89c9ab8e8298c7df716a047c9cf481a64aed6 and a reboot seems to have fixed the 'native hook not found' issue (haven't tested any further).

@wait-what I've attached my build, but I recommend building it yourself (or wait for an official release) if possible, it's relatively easy to do
 [app-debug.zip](https://github.com/nfcgate/nfcgate/files/14186670/app-debug.zip)

**Comment by roussosalex** [comment]
@i404788 Thank you for verifying!
