### ISSUE TITLE
Native hook not available on Galaxy M31 (Magisk, Rooted, LSposed)

### ISSUE THREAD

**Issue by BenEgeDeniz** [nfcgate/nfcgate#141]
**App Information\***
Screenshot of "status" page
![Screenshot_20231126-214545_NFCGate](https://github.com/nfcgate/nfcgate/assets/59136798/f3a27e67-cb16-4922-8fa1-49dcae8758a2)

**Device Information\*
Device: Samsung Galaxy M31
OS: Android 12 (stock, oneui)

**Log\***
[logcat1.txt](https://github.com/nfcgate/nfcgate/files/13467744/logcat1.txt)

**Additional context**
Tried relay attack on tag mode with a contactless payment card, POS device didnt recognize it as a payment card. All my setup is correct. The only reason should be the native hook.

**Comment by balltobi** [comment]
Exactly the same issue for Samsung Galaxy S20FE, works fine with same setup on other devices

**Comment by BenEgeDeniz** [comment]
I have checked the status page again and the native hook seemed to be enabled. I restarted the phone and it turned back to the yellow questionmark.

**Comment by roussosalex** [comment]
Thanks for reporting! This issue seems a bit mysterious, because the log really has no "fatal" errors. Something Samsung-specific might be going on with the NFC startup that is not "standard". Could you try: 

* reboot the device
* open NFCGate
* if the question mark is yellow:
  * turn off NFC, wait a bit, turn NFC back on
  * force stop/kill NFCGate, wait a bit, open NFCGate again
  * check question mark again.  Report back on what happens

In any case, please try to pull the log from boot after this process and attach it.

**Comment by roussosalex** [comment]
@balltobi Please attach a boot log so we can try to better understand the issue

**Comment by BenEgeDeniz** [comment]
Now the native hook seems to be enabled. But I can't emulate a 4 byte UID.
I am trying to use NFCGate in Clone Tag mode and with the emulation on, my phone' UID changes to 4 bytes of 0x00 (00-00-00-00).
BUT there is some hope. It actually can modify my UID like that AND STILL MORE, it successfully emulates a contactless payment card' 7 byte UID perfectly every single time.

So, why can it emulate a 7 byte UID while it can't emulate a 4 byte UID?

**Comment by BenEgeDeniz** [comment]
Yepi now I see why. Google is kinda dumb. They actually made it impossible to emulate any Mifare Classic 1K type cards. I can emulate a JCOP30 card with a 4 byte uid.

**Comment by roussosalex** [comment]
> Now the native hook seems to be enabled.

Can you confirm that the native hook now works as expected, with no extra steps required?

> They actually made it impossible to emulate any Mifare Classic 1K type cards.  

Android no longer offers support for MiFare classic, so these cards are not supported

**Comment by BenEgeDeniz** [comment]
> > Now the native hook seems to be enabled.
> 
> Can you confirm that the native hook now works as expected, with no extra steps required?
> 
> > They actually made it impossible to emulate any Mifare Classic 1K type cards.
> 
> Android no longer offers support for MiFare classic, so these cards are not supported

Nope, when I reboot the phone, native hook went away again.

**Comment by roussosalex** [comment]
Did you try the steps I suggested above after rebooting the phone?

**Comment by BenEgeDeniz** [comment]
> Did you try the steps I suggested above after rebooting the phone?

Yes, I did. Even if the native hook is not working, cloning a tag works well.

**Comment by roussosalex** [comment]
If cloning works, the native hook must be working as well. Could you please share another log when the cloning is successful? It's possible that the UI is incorrectly displaying the status of the native hook. Your cooperation is greatly appreciated.

**Comment by BenEgeDeniz** [comment]
I only checked the UID, and it worked. I think cloning only emulates only the UID and tag type, am I correct?

If yes, please give me further instructions about saving a log file of NFCGate.

**Comment by kleest** [comment]
> I think cloning only emulates only the UID and tag type, am I correct?

That's correct. 

> If yes, please give me further instructions about saving a log file of NFCGate.

Just a regular ADB logcat like you shared previously. Thanks!

**Comment by roussosalex** [comment]
See #146

**Comment by devath0** [comment]
> See #146

This build version not working today
