### ISSUE TITLE
Native hook could not be found [Samsung SM-J730FM/DS]

### ISSUE THREAD

**Issue by mr7Ouroboros** [nfcgate/nfcgate#147]
**App Information\***
Screenshot of "status" page
![photo_2024-01-25_21-26-53 (2)](https://github.com/nfcgate/nfcgate/assets/157714640/1d7203a1-68d9-49e4-8431-1083862d051d)![photo_2024-01-25_21-26-53 (3)](https://github.com/nfcgate/nfcgate/assets/157714640/2f511913-3cba-49a0-b2d3-cd9d82751edb)
![photo_2024-01-25_21-26-53 (4)](https://github.com/nfcgate/nfcgate/assets/157714640/ad9c32b6-3b0a-460b-827e-4d3a99c092f5)

**Device Information\***
Device: Samsung SM-J730FM/DS  
OS: Android 9

**Log\***
Test 1: [log-1.txt](https://github.com/nfcgate/nfcgate/files/14058326/log-1.txt)
Test 2: [log-2.txt](https://github.com/nfcgate/nfcgate/files/14058368/log-2.txt)

**Additional context**
Hello, can you please advise me how to solve the problem with the native hook on my device?

**Comment by mr7Ouroboros** [comment]
This problem is solved, tried following the steps in this comment and the hook turned green
https://github.com/nfcgate/nfcgate/issues/141#issuecomment-1858687405

**Comment by mr7Ouroboros** [comment]
The retransmission of traffic is slow, can you tell me if there are no timeouts or delays for retransmission in the source code?

**Comment by kleest** [comment]
@mr7Ouroboros The network code uses a regular TCP connection with no additional retransmission or delay logic.

**Comment by mr7Ouroboros** [comment]
If you replace Google Protocol Buffers with websocket, will it work?

**Comment by mr7Ouroboros** [comment]
Hi, can you tell me the difference between v2.3.0 and v2.3.0-rc ?

**Comment by roussosalex** [comment]
@mr7Ouroboros the `v2.3.0` has d2937334349e5d8c9e0c9b11f7db901f0bdf9fca and some very minor changes compared to the release candidate.

**Comment by mr7Ouroboros** [comment]
After rebooting the problem with native hook started again, please advise, is it only in samsungs such a problem? What smartphones do not have this problem? Tired of this problem already, I think just change the smartphone.
Tell me which smartphones do not have problems with native hooks.

**Comment by roussosalex** [comment]
There is a Samsung-specific issue at the moment with several devices, we are actively working on a fix (see #146). If you want to try another device in the meantime, see the [compatibility matrix](/nfcgate/nfcgate/blob/v2/doc/Compatibility.md#matrix) for suggestions

**Comment by roussosalex** [comment]
@mr7Ouroboros Please try the new development version on the `v2-dev` branch and see if it fixes the native hook issue on your Samsung device.

**Comment by kleest** [comment]
You can find a compiled version attached to [my comment in the other issue](https://github.com/nfcgate/nfcgate/issues/146#issuecomment-1944757296).
