### ISSUE TITLE
Please rezolve with protobuf sync  in server

### ISSUE THREAD

**Issue by Barladulos** [nfcgate/nfcgate#150]
I like your work, I'm a beginner with security and I want to tell you that I managed to compile the old application plus server and phones and it works with the old protobuf, now with this update to the application and protobuf I can't compile it. and finally the published version of the apk type application.
When you are connected with the application, it gives me an instruction error (6D 00) and does not open the payment terminal.
Could  you help me please ? Could update apk version on git hub, please ?
Thank you in advance, and and many appreciations for the work done.
![Screenshot 2024-02-02 132552](https://github.com/nfcgate/nfcgate/assets/158513568/58db8c08-dc5d-41dc-9204-989442126a0b)
![Screenshot 2024-02-02 132657](https://github.com/nfcgate/nfcgate/assets/158513568/3b950605-128a-4c02-914a-432ee20494ba)
![Screenshot 2024-02-02 132728](https://github.com/nfcgate/nfcgate/assets/158513568/925bc5df-59c8-4596-98a3-fc061b873da8)
![Screenshot 2024-02-02 132800](https://github.com/nfcgate/nfcgate/assets/158513568/150c3554-f75b-4bf7-8023-80e942c828bc)

My phones are 2 samsung galaxy a5 2018 with android 10 , root with magisk , module edexposed work , no problems with native hook.
Thanks a lot for helping me.

**Comment by roussosalex** [comment]
Hello, not sure I understand the issue. Did you pull the git submodule before building? If not, try:  
`git submodule update --init --recursive`

**Comment by Barladulos** [comment]
Yes that it was. Thank you, i apreiceted that. 
Great work. I`m comming with new issues if i found!

**Comment by Barladulos** [comment]
Hello! Guys when i m trying to get the apk and  show me CXX1429 error i m trying to update sdk and cmake and it doesn t work. Could you help me ?

![Screenshot 2024-02-03 135511](https://github.com/nfcgate/nfcgate/assets/158513568/f56bef50-ac78-44e5-a7e4-7fe18fda9428)

I m waiting for your help, thank you!
