### ISSUE TITLE
Native hook issues with SM-A526B

### ISSUE THREAD

**Issue by cydef1** [nfcgate/nfcgate#156]
**App Information***

![status](https://github.com/nfcgate/nfcgate/assets/51300087/8e0f2fc4-95dd-432f-ae46-1bcc1f9e8fb1)

**Device Information*** 

Samsung Galaxy A52 5G (SM-A526B)

OS:   Android OS 13

**Log***
![log](https://github.com/nfcgate/nfcgate/assets/51300087/741fbed9-4c64-45c4-9b37-ed50c52cfe1c)

**Comment by roussosalex** [comment]
Thanks for contributing!

Your issue looks like this other Samsung-specific issue: #146. Please try the debug-version linked here: https://github.com/nfcgate/nfcgate/issues/146#issuecomment-1944757296. We will soon incorporate this into a future release.

**Comment by cydef1** [comment]
![image](https://github.com/nfcgate/nfcgate/assets/51300087/5ecddc91-de69-4125-8b77-18c6e5daed18)

**Comment by cydef1** [comment]
Now it works perfectly

**Comment by Lassie111** [comment]
> Now it works perfectly

@cydef1 Does the cloning work correctly though? For my device even after Native hook is enabled, the NFC chip does not accept the NFCID and presents a random one instead (#153).

I wonder if it is a problem with my device only or with all Samsung devices.

**Comment by roussosalex** [comment]
@Lassie111 It looks like the behavior you are describing has nothing to do with Samsung devices and everything to do with the type of NFC Chip. Your NXP chip has the same issues as many OnePlus models with the same chip (i.e. it only uses random NFCIDs and does not accept a manually set one). @cydef1 has a Samsung NFC chip, where that issue has never been reported so far.
