### ISSUE TITLE
network.c2c.C2C.NFCData; is missing

### ISSUE THREAD

**Issue by priyazakapps** [nfcgate/nfcgate#157]
**Describe the bug**

A clear and concise description of the bug. What is happening that is not supposed to? Or vice versa.

**App Information***

Please provide a screenshot of the "status" page

**Device Information*** Which device are you using and what OS are you running on it?

Device: [e.g. Google Pixel 7]

OS: [e.g. Android 14]

**Log***

Attach a boot log (system logcat since boot).
See [here](https://www.xda-developers.com/how-to-take-logs-android/#system-logs) for detailed
instructions.

**Steps to reproduce**

Please describe the steps taken to reproduce the problem.
Be as descriptive as can you be, e.g.:

**Expected behavior**

A clear and concise description of what you expect to happen.

**Observed/unwanted behavior**

What is the behavior that is occurring?

**Screenshots**

Optionally, add screenshots to help show the problem.

**Additional context**

**Proposed solution**

If you have thought about a solution for the problem, please elaborate here!

**Comment by roussosalex** [comment]
Looks like you did not follow the first step for building the project [from the README](https://github.com/nfcgate/nfcgate?tab=readme-ov-file#building). Please fill out the bug report template properly next time.
