### ISSUE TITLE
Please update instructions / EdXposed and Magisk "Downloads" unavailable

### ISSUE THREAD

**Issue by xsrf** [nfcgate/nfcgate#167]
**Describe the bug**

I can't get required software to work because of outdated instructions

**App Information***

- Xposed Module Enabled: ?
- Native Hook Enabled: ?

Banner "Warning: Xposed module is not working properly"

**Device Information*** Which device are you using and what OS are you running on it?

Device: Google Nexus 5X

OS: Android 8.1.0 rooted with Magisk 25.2 / (also tested 27.0)

**Steps to reproduce**

EdXposed stable is only available in the Magisk "Downloads" Tab which it was removed some time ago, so it can't be installed.
EdXposed alpha is available as zip, but install via Magisk fails because it insists it wants riru from Magisk "Downloads" Tab which doesn't exist and rirus regular install (which is available as zip) wasn't recognized by EdXposed alpha install script.

LSPosed can be downloaded as zip and installed in Zygisc mode but is not recognized by NFCGate.
LSPosed can also be installed in riru mode but is also not recognized by NFCGate.

I never get a Superuser request for NFCGate btw.

**Expected behavior**

Instructions should work

**Screenshots**
Device 1

<img src="https://github.com/nfcgate/nfcgate/assets/8081353/20be6756-2fe9-4422-98e0-0bb5be3c51b2" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/cd373256-c6ff-407d-8fbb-ce331c69456a" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/6e23d1c0-2f0e-40cb-8591-ce520b16ac9f" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/ed014e9f-c05e-4a7a-9e54-e53f7ab6c187" width="180">

Device 2

<img src="https://github.com/nfcgate/nfcgate/assets/8081353/f337cc38-65ae-4945-84c9-4b38c348fd3c" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/f6b309f3-e6c0-4c12-9628-191a64f4fe20" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/ed8cf63c-4637-41b7-9389-8608329612c0" width="180">
<img src="https://github.com/nfcgate/nfcgate/assets/8081353/807c0ac3-3ed8-44ec-860b-4433b3ad70df" width="180">

**Comment by Tomatcree01** [comment]
You didn't properly quit and then activate. I am able to get it to detect the xposed environment but not native hooks...

**Comment by xsrf** [comment]
@Tomatcree01 the phones rebooted several times by now, that shouldn't be an issue

Attaches is the logcat after `killall com.android.nfc`: [logcat_nfc_kill.txt](https://github.com/user-attachments/files/15856512/logcat_nfc_kill.txt)

I cannot find any `NATIVENFC` or `Library found at` in the complete logcat since reboot (as mentioned in #131)

**Comment by kleest** [comment]
Did you enable the module in the *posed module manager? At least LSposed requires you to tick the app/service for which you want to enable the module. NFCGate lists com.android.nfc as a suggestion there. After the module is enabled the NFC service must be restarted either by killing it or restarting the device.
We had great success using NFCGate on the Nexus 5X with the same ROM version. It was one of the primary development devices. Using NFCGate there should be straightforward: Install Magisk, install LSposed, install NFCGate, enable the module in LSposed manager, kill NFC service.

**Comment by kleest** [comment]
> You didn't properly quit and then activate. I am able to get it to detect the xposed environment but not native hooks...

@Tomatcree01 If xposed module is shown as enabled but the native hook is not active, please open a separate issue with logs.

**Comment by xsrf** [comment]
These Tools really require lots of prior knowledge. I didn't enable a Module in LSposed Manager. I didn't even know it exists. On the ruri version there is also no notification to open the manager.
I enabled the module and now all checks are green. Guess it works, thx.
Would be nice if this could be mentioned in the readme. I've done lots of android related development but never used *posed and this is not at all obvious.

**Comment by kleest** [comment]
Since devices and instructions to install and use  *posed frameworks on those are very diverse, we refrain from adding specific instructions to the readme which might not universally apply. The idea is to keep the readme rather simple and treat dependencies and requirements as a blackbox. So, we send the user to the frameworks where they find specific instructions. For example, how to use LSposed is described in [its wiki](https://github.com/LSPosed/LSPosed/wiki/How-to-use-it).

We consider improving the instructions and UX of the onboarding process, thanks for your input! If additional problems arise, feel free to re-open or create a new issue.

**Comment by xsrf** [comment]
At least noting that EdXposed is not available anymore via the documented sources would have saved me lots of time though

**Comment by Tomatcree01** [comment]
> > You didn't properly quit and then activate. I am able to get it to detect the xposed environment but not native hooks...
> 
> @Tomatcree01 If xposed module is shown as enabled but the native hook is not active, please open a separate issue with logs.

I managed to get it to work lol
