### ISSUE TITLE
CMake Error at CMakeLists.txt:7 (add_library): No SOURCES given to target: xh

### ISSUE THREAD

**Issue by 974946750** [nfcgate/nfcgate#171]
The XH library is empty

**Comment by 974946750** [comment]
When I put the file of xHook in D: \ AndroidProject \ nfcgate-2 \ nfcd \ xHook, it prompts that there is no NFCData;
import de.tu_darmstadt.seemoo.nfcgate.network.c2c.C2C.NFCData; There is no such file

**Comment by kleest** [comment]
Follow [the instructions](https://github.com/nfcgate/nfcgate?tab=readme-ov-file#building) to initialize git submodules.
