### ISSUE TITLE
On-Device Capture Mode

### ISSUE THREAD

**Issue by xcypher78** [nfcgate/nfcgate#175]
Hello, When I try capture mode and use a third-party app and click on stop capture, the nfcgate app jumps out and give me a fail popup

**Comment by roussosalex** [comment]
Thanks for reporting this issue. Please attach a log (see [here](https://www.xda-developers.com/how-to-take-logs-android/#system-logs) for detailed instructions) and post a screenshot of the "fail popup" to help us identify the issue.

**Comment by kleest** [comment]
We [added a commit](https://github.com/nfcgate/nfcgate/commit/e6c98af244a7f43340b5c090f2e35d96451b02d6) that affects on-device capture mode. Could you please test if the most recent default branch version works? If not, please attach a log as mentioned in the previous comment.

You can find the most recent automatically created APK [in the workflow run details on the actions tab](https://github.com/nfcgate/nfcgate/actions/workflows/build-android.yml).

**Comment by xcypher78** [comment]
when i installed for the first time this app work correctly, now keep still not work

**Comment by roussosalex** [comment]
Please attach a log (see [here](https://www.xda-developers.com/how-to-take-logs-android/#system-logs) for detailed instructions) and post a screenshot of the "fail popup" to help us identify the issue.

**Comment by xcypher78** [comment]
i will close this because i choose other third-party reader and work again 

anyway thanks
