### ISSUE TITLE
Poco X3 Pro "Xposed module not working properly"

### ISSUE THREAD

**Issue by deep2web** [nfcgate/nfcgate#181]
**App Information***

![Screenshot_20241009-234633_Pixel Launcher.png](https://github.com/user-attachments/assets/7c2f5961-ca75-475e-a8df-5b7bf1037640)

**Device Information*** Which device are you using and what OS are you running on it?

Device: Poco X3 Pro 8GB 256GB

OS: ![Screenshot_20241010-000014_Pixel Launcher.png](https://github.com/user-attachments/assets/f9c99160-db75-4434-b6f5-f67f213a37a9)

**Log***

![logcat.txt](https://github.com/user-attachments/files/17319738/logcat.txt)

![09_10-23-48-47_531.txt](https://github.com/user-attachments/files/17319739/09_10-23-48-47_531.txt)

**Additional context**

LSPosed: ![Screenshot_20241010-000137_Pixel Launcher.png](https://github.com/user-attachments/assets/77909a77-3272-4c2d-bbea-7b4a1447d657)

HCEF unlocker is not installed, because NFCGate shows HCE as enabled.

**Comment by kleest** [comment]
Could you please try out the latest v2 branch version? Please see the [actions page](https://github.com/nfcgate/nfcgate/actions) for downloads.

**Comment by deep2web** [comment]
Thanks! With the latest V2 branch version everything now works perfect!
