### ISSUE TITLE
Android 15 defaults app to edge-to-edge mode

### ISSUE THREAD

**Issue by linsui** [nfcgate/nfcgate#187]
**Describe the bug**

![Screenshot_20241210-181021_NFCGate](https://github.com/user-attachments/assets/6cc3cd1e-7164-4071-b30c-a71cb156e1fa)

**App Information***

Please provide a screenshot of the "status" page

**Device Information*** Which device are you using and what OS are you running on it?

Device: [e.g. Google Pixel 7]

OS: [e.g. Android 14]

**Log***

Attach a boot log (system logcat since boot).
See [here](https://www.xda-developers.com/how-to-take-logs-android/#system-logs) for detailed
instructions.

**Steps to reproduce**

Please describe the steps taken to reproduce the problem.
Be as descriptive as can you be, e.g.:

**Expected behavior**

A clear and concise description of what you expect to happen.

**Observed/unwanted behavior**

What is the behavior that is occurring?

**Screenshots**

Optionally, add screenshots to help show the problem.

**Additional context**

**Proposed solution**

If you have thought about a solution for the problem, please elaborate here!

**Comment by weebl2000** [comment]
Noticed the same on Pixel 6 with latest build AP4A.241205.013.A2

**Comment by kleest** [comment]
Thank you for creating an issue. I fixed it by reverting to the previous targetSdkVersion for now until we have a proper solution.

**Comment by linsui** [comment]
Thanks!
