### ISSUE TITLE
New connection types (reduce latency)

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#43]
Possible ways to reduce latency:
- Bluetooth
- WiFi direct
- [Ethernet via USB](https://android.stackexchange.com/questions/2298/how-to-set-up-reverse-tethering-over-usb/6480#6480)

**Comment by roussosalex** [comment]
The current architecture uses the system connection and can already use different types of network. This is the most flexible approach and requires no additional work on the app itself.
