### ISSUE TITLE
Rule-based replacement of NFC commands

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#45]
We could log all NFC commands and display them in a list. Then, we could let the user create rules to change these requests on the fly (e.g. replace certain bytes, drop messages, ...) to see what happens and try to find holes in the protocols.

There is obviously a certain risk of bricking a card with that, but it would be worth a try, IMO. Somewhat related to #38.

**Comment by kleest** [comment]
Device filters have been dropped in favor of scriptable server filters in [v2](/nfcgate/nfcgate/tree/v2).
