### ISSUE TITLE
Develop alternate native patch method for Android 5 / ART

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#57]
Substrate does not support Android 5 / ART. We should think about how we could provide the required native code patches without Substrate.

The current ideas are:
- Ship our own compiled libnfc and switch it out when the app becomes active
- Ship our own compiled libnfc parts, exporting all symbols, and forward unmodified symbols to original libnfc
- Ship our own compiled libnfc, export only modified symbols and shadow existing symbols with them
- Try injectso again 

Appearently, XPosed works with Android 5, but, right now, only if you manually flash it (can't just install via the Play Store). If that changes, we could consider using it for the Java patch, but if this stays the same, we may have to find another way to fool the java `findSelectAid` function.

**Comment by malexmave** [comment]
See [the android-5 branch](https://github.com/nfcgate/nfcgate/tree/android-5) for current state of development on this.

**Comment by UweM** [comment]
android-5 branch is working and merged into dev
