### ISSUE TITLE
Investigate where the Workaround is needed

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#64]
Appearently, the workaround is also needed for the chip used in the OnePlus One, at the very least. We should investigate if it may be universally needed, and if not, for which devices it is needed.

@DanielAW also proposes a button in the settings to disable the workaround if it causes problems.

I enabled the Workaround by default for all devices for now (see 58b62da)

**Comment by UweM** [comment]
Maybe we can disable the workaround as soon as one command was relayed to the card. I think the card should stay in the same mode as suggested by that first apdu.
