### ISSUE TITLE
Workaround thread management

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#65]
Currently, there are some cases when the workaround thread is not killed and becomes unkillable via the GUI. They appearently include:
- "Leave Session"
- ... (if you find more such cases, document them here)

We should fix that.

**Comment by kleest** [comment]
Workaround has been disabled in [v2](/nfcgate/nfcgate/tree/v2) due to no issue in newer Android versions, reopen if issue persists.
