### ISSUE TITLE
Implement and test WTX routine

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#66]
From [this source](http://mhutter.org/papers/Issovits2011WeaknessesOfThe.pdf):

> The ISO/IEC 14443 standard defines a Waiting Time Extension (WTX) command. This command can be used by a PICC to request more time to prepare the response.

This is the active counterpart to #53, and it is not part of the Anticol loop, so we may be able to use this to increase the time we have to get our reply out to the reader.

**Comment by roussosalex** [comment]
Since WTX is implemented in ISO/IEC 14443 with a different type of block (S-Block instead of I-Block for APDUs) we cannot influence this directly and should instead try to use the passive method in #53.
