### ISSUE TITLE
GUI for Filter Selection

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#69]
Now that we have a basic filter infrastructure in place (see #45 / #63), we need a way to use it from the GUI. However, since we are also planning more advanced Filter features, I am not sure if it is worth building a GUI for the basic ones now, and then completely re-writing it once the advanced filters arrive... Any opinions?

**Comment by kleest** [comment]
Device filters have been dropped in favor of scriptable server filters in [v2](/nfcgate/nfcgate/tree/v2).
