### ISSUE TITLE
Split RelayFragment into multiple Fragments

### ISSUE THREAD

**Issue by malexmave** [nfcgate/nfcgate#72]
Currently, the RelayFragment contains all the UI elements to establish a network connection, but it also contains the DebugWindow.

As far as I understand Fragments, best practise would be to implement other connection types in their own fragments. This would involve redundant code if each of these fragments would have to contain the DebugWindow. Instead, we could split the fragment into one ProtobufConnectionFragment (or something like that) and one DebugOutputFragment. We could then swap out the first fragment on demand and replace it with other fragments for Bluetooth or whichever other technologies we implement.

This would also allow us to completely replace the debug window with another fragment if it is deactivated (e.g. a small section with instructions, or a more detailed / better-designed display of the connection status), thereby easily using the screen real estate productively if the debug window is not activated, instead of leaving it empty.

This is probably a large change involving quite a bit of work, but it lays the foundations for easier implementations of other connection technologies later. Any opinions?

**Comment by kleest** [comment]
GUI heavily reworked, so this no longer applies in [v2](/nfcgate/nfcgate/tree/v2).
