### ISSUE TITLE
NetworkOnMainThreadException on Android 7

### ISSUE THREAD

**Issue by zhangyoufu** [nfcgate/nfcgate#95]
> Due to a bug in previous versions of Android, the system did not flag writing to a TCP socket on the main thread as a strict-mode violation. Android 7.0 fixes this bug. Apps that exhibit this behavior now throw an android.os.NetworkOnMainThreadException. Generally, performing network operations on the main thread is a bad idea because these operations usually have a high latency that causes ANRs and jank.

**Comment by malexmave** [comment]
Huh, that's interesting. I am pretty sure we put all networking on a separate thread by now. When and where do you get the error? (I currently don't have an Android 7 device on hand).

Generally, NFCGate will not function properly on Android 7, at least until there is an XPosed version that works on Android 7.

**Comment by roussosalex** [comment]
Fixed in [v2](/nfcgate/nfcgate/tree/v2) branch.
